import com.bradescoa3.integration.TelaIntegration;
import com.bradescoa3.integration.AdminIntegration;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author conta
 */
public class telaAdmin extends javax.swing.JFrame {

    // Integração com a lógica de negócio
    private final TelaIntegration integration;
    
    /**
     * Creates new form telaAdmin
     */
    public telaAdmin() {
        initComponents();
        setLocationRelativeTo(null);
        
        // Inicializa a integração
        integration = new TelaIntegration();
        
        // Carrega as denúncias na tabela
        carregarDenuncias();
        
        // Habilita o botão de remover quando uma linha é selecionada
        tblDenunciados.getSelectionModel().addListSelectionListener(e -> {
            btnRemover.setEnabled(tblDenunciados.getSelectedRow() != -1);
        });
    }
    
    /**
     * Carrega as denúncias do banco de dados na tabela
     */
    private void carregarDenuncias() {
        try {
            // Obtém os dados das denúncias
            Object[][] dados = integration.carregarDenuncias(this);
            
            if (dados != null) {
                // Cria um modelo de tabela com os dados
                DefaultTableModel modelo = new DefaultTableModel(
                        dados,
                        new String[]{"CPF/CNPJ", "NOME", "MOTIVO"}
                ) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        return false; // Impede a edição das células
                    }
                };
                
                // Define o modelo na tabela
                tblDenunciados.setModel(modelo);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Erro ao carregar denúncias: " + e.getMessage(), 
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdmin = new javax.swing.JPanel();
        lblAdministrador = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        spnlTabela = new javax.swing.JScrollPane();
        tblDenunciados = new javax.swing.JTable();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        lblAdministrador.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdministrador.setText("ADMINISTRADOR");

        tblDenunciados.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        tblDenunciados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CPF/CNPJ", "NOME", "MOTIVO"
            }
        ));
        spnlTabela.setViewportView(tblDenunciados);

        btnRemover.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnRemover.setText("Remover Conta");
        btnRemover.setEnabled(false);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminLayout = new javax.swing.GroupLayout(pnlAdmin);
        pnlAdmin.setLayout(pnlAdminLayout);
        pnlAdminLayout.setHorizontalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(lblAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(spnlTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addComponent(btnRemover)
                .addGap(140, 140, 140))
        );
        pnlAdminLayout.setVerticalGroup(
            pnlAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnlTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        try {
            // Verifica se há uma linha selecionada
            int linhaSelecionada = tblDenunciados.getSelectedRow();
            if (linhaSelecionada == -1) {
                JOptionPane.showMessageDialog(this, 
                        "Selecione uma denúncia para remover.", 
                        "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Obtém o CPF/CNPJ da linha selecionada (primeira coluna)
            String cpfCnpj = tblDenunciados.getValueAt(linhaSelecionada, 0).toString();
            
            // Confirma a remoção
            int confirmacao = JOptionPane.showConfirmDialog(this, 
                    "Tem certeza que deseja remover a denúncia do CPF/CNPJ " + cpfCnpj + "?", 
                    "Confirmar Remoção", JOptionPane.YES_NO_OPTION);
            
            if (confirmacao == JOptionPane.YES_OPTION) {
                // Remove a denúncia
                boolean sucesso = integration.removerDenuncia(cpfCnpj, this);
                
                if (sucesso) {
                    // Recarrega a tabela
                    carregarDenuncias();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Erro ao remover denúncia: " + e.getMessage(), 
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemover;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAdministrador;
    private javax.swing.JPanel pnlAdmin;
    private javax.swing.JScrollPane spnlTabela;
    private javax.swing.JTable tblDenunciados;
    // End of variables declaration//GEN-END:variables
}
