import com.bradescoa3.integration.TelaIntegration;
import com.bradescoa3.model.Usuario;
import com.bradescoa3.util.SessaoUsuario;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author conta
 */
public class telaDenuncia extends javax.swing.JFrame {

    // Integração com a lógica de negócio
    private final TelaIntegration integration;
    
    /**
     * Creates new form telaDenuncia
     */
    public telaDenuncia() {
        initComponents();
        setLocationRelativeTo(null);
        
        // Inicializa a integração
        integration = new TelaIntegration();
        
        // Configura o campo de CPF/CNPJ para formatação automática
        integration.configurarCampos(txtCpfDestino, null);
        
        // Verifica se há usuário logado
        Usuario usuarioLogado = integration.getUsuarioLogado();
        if (usuarioLogado == null) {
            JOptionPane.showMessageDialog(this, 
                    "Nenhum usuário logado. Redirecionando para a tela de login.", 
                    "Erro de Sessão", 
                    JOptionPane.ERROR_MESSAGE);
            
            // Redireciona para a tela de login
            telaLogin login = new telaLogin();
            login.setVisible(true);
            this.dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDenunciar = new javax.swing.JPanel();
        scrMotivo = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        txtCpfDestino = new javax.swing.JTextField();
        lblCpfDestino = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        lblDenunciar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMotivoDenuncia = new javax.swing.JLabel();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Denunciar");

        txtMotivo.setColumns(20);
        txtMotivo.setRows(5);
        scrMotivo.setViewportView(txtMotivo);

        txtCpfDestino.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        lblCpfDestino.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblCpfDestino.setText("CPF/CNPJ");
        lblCpfDestino.setToolTipText("");
        lblCpfDestino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCpfDestino.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblSenha.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblSenha.setText("Sua senha:");
        lblSenha.setToolTipText("");
        lblSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblSenha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtSenha.setMinimumSize(new java.awt.Dimension(64, 23));

        lblDenunciar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblDenunciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDenunciar.setText("DENUNCIAR");

        lblMotivoDenuncia.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        lblMotivoDenuncia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMotivoDenuncia.setText("Motivo da denuncia:");
        lblMotivoDenuncia.setToolTipText("");
        lblMotivoDenuncia.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblMotivoDenuncia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDenunciarLayout = new javax.swing.GroupLayout(pnlDenunciar);
        pnlDenunciar.setLayout(pnlDenunciarLayout);
        pnlDenunciarLayout.setHorizontalGroup(
            pnlDenunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDenunciarLayout.createSequentialGroup()
                .addGroup(pnlDenunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDenunciarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMotivoDenuncia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlDenunciarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrMotivo, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                    .addComponent(lblDenunciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDenunciarLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlDenunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(pnlDenunciarLayout.createSequentialGroup()
                                .addGroup(pnlDenunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCpfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlDenunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCpfDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
            .addGroup(pnlDenunciarLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnEnviar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDenunciarLayout.setVerticalGroup(
            pnlDenunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDenunciarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDenunciar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(pnlDenunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCpfDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCpfDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDenunciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMotivoDenuncia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDenunciar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlDenunciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // Obtém os dados dos campos
        String cpfCnpjDenunciado = txtCpfDestino.getText();
        String motivo = txtMotivo.getText();
        String senha = new String(txtSenha.getPassword());
        
        // Tenta registrar a denúncia
        boolean sucesso = integration.registrarDenuncia(cpfCnpjDenunciado, motivo, senha, this);
        
        if (sucesso) {
            // Volta para o menu principal
            telaMenu menu = new telaMenu();
            menu.setVisible(true);
            this.dispose(); // Fecha a tela de denúncia
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaDenuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaDenuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaDenuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaDenuncia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaDenuncia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCpfDestino;
    private javax.swing.JLabel lblDenunciar;
    private javax.swing.JLabel lblMotivoDenuncia;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel pnlDenunciar;
    private javax.swing.JScrollPane scrMotivo;
    private javax.swing.JTextField txtCpfDestino;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
