import com.bradescoa3.integration.TelaIntegration;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author conta
 */
public class telaRecuperar extends javax.swing.JFrame {

    // Integração com a lógica de negócio
    private final TelaIntegration integration;
    
    /**
     * Creates new form telaRecuperar
     */
    public telaRecuperar() {
        initComponents();
        setLocationRelativeTo(null);
        
        // Inicializa a integração
        integration = new TelaIntegration();
        
        // Configura o campo de CPF/CNPJ para formatação automática
        integration.configurarCampos(txtLogin, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlRecuperarSenha = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblNovaSenha = new javax.swing.JLabel();
        txtNovaSenha = new javax.swing.JPasswordField();
        lblConfirmarSenha = new javax.swing.JLabel();
        txtConfirmarSenha = new javax.swing.JPasswordField();
        btnRecuperarLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperar login");

        lblTitulo.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("RECUPERAR LOGIN");

        lblLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLogin.setText("CPF:");

        lblNovaSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblNovaSenha.setText("NOVA SENHA");

        lblConfirmarSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblConfirmarSenha.setText("CONFIRMAR");

        btnRecuperarLogin.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnRecuperarLogin.setText("Recuperar login");
        btnRecuperarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecuperarLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRecuperarSenhaLayout = new javax.swing.GroupLayout(pnlRecuperarSenha);
        pnlRecuperarSenha.setLayout(pnlRecuperarSenhaLayout);
        pnlRecuperarSenhaLayout.setHorizontalGroup(
            pnlRecuperarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRecuperarSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlRecuperarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecuperarSenhaLayout.createSequentialGroup()
                        .addGroup(pnlRecuperarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblConfirmarSenha)
                            .addComponent(lblNovaSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlRecuperarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRecuperarLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNovaSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLogin, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        pnlRecuperarSenhaLayout.setVerticalGroup(
            pnlRecuperarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecuperarSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRecuperarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRecuperarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNovaSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRecuperarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblConfirmarSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecuperarLogin)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRecuperarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlRecuperarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecuperarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecuperarLoginActionPerformed
        try {
            // Obtém os dados dos campos
            String cpfCnpj = txtLogin.getText();
            String novaSenha = new String(txtNovaSenha.getPassword());
            String confirmarSenha = new String(txtConfirmarSenha.getPassword());
            
            // Valida os campos
            if (cpfCnpj.isEmpty() || novaSenha.isEmpty() || confirmarSenha.isEmpty()) {
                JOptionPane.showMessageDialog(this, 
                        "Todos os campos são obrigatórios.", 
                        "Erro de Recuperação", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // Verifica se as senhas coincidem
            if (!novaSenha.equals(confirmarSenha)) {
                JOptionPane.showMessageDialog(this, 
                        "As senhas não coincidem.", 
                        "Erro de Recuperação", JOptionPane.ERROR_MESSAGE);
                txtNovaSenha.setText("");
                txtConfirmarSenha.setText("");
                txtNovaSenha.requestFocus();
                return;
            }
            
            // Tenta atualizar a senha
            boolean sucesso = integration.atualizarSenha(cpfCnpj, novaSenha, this);
            
            if (sucesso) {
                // Abre a tela de login
                telaLogin login = new telaLogin();
                login.setVisible(true);
                this.dispose(); // Fecha a tela de recuperação
            } else {
                // Limpa os campos de senha e dá foco ao campo de CPF/CNPJ
                txtNovaSenha.setText("");
                txtConfirmarSenha.setText("");
                txtLogin.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                    "Erro ao recuperar login: " + e.getMessage(), 
                    "Erro", JOptionPane.ERROR_MESSAGE);
            // Limpa os campos de senha
            txtNovaSenha.setText("");
            txtConfirmarSenha.setText("");
        }
    }//GEN-LAST:event_btnRecuperarLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaRecuperar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaRecuperar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaRecuperar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaRecuperar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaRecuperar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecuperarLogin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblConfirmarSenha;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNovaSenha;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlRecuperarSenha;
    private javax.swing.JPasswordField txtConfirmarSenha;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtNovaSenha;
    // End of variables declaration//GEN-END:variables
}
